config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  # GET /articles
  def index
    @flats = Flat.all
  end

  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @flat = Flat.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to @flat, notice: 'A new flat was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @flat.update(flat_params)
      redirect_to @flat, notice: 'The flat was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @flat.destroy
    redirect_to flats_url, notice: 'The flat was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def flat_params
      params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h1>Flats#edit</h1>
<p>Find me in app/views/flats/edit.html.erb</p>

app/views/flats/index.html.erb
<div class="container">
  <div class="content mt-3">
    <h1>Flats Listing</h1>
    <div class="row">
      <% @flats.each do |flat| %>
        <div class="col-4">
          <div class="flat-card">
        <h1><%= flat.name %></h1>
        <h2> <%= flat.address %> </h2>
        <h3><%= flat.description %> </h3>
        <h2> <%= flat.price_per_night %> </h2>
        <h2> <%= flat.number_of_guests %> </h2>

        <%= link_to 'more infos', flat_path(flat), class: "btn btn-success" %>
        <%= link_to 'edit', edit_flat_path(flat), class: "btn btn-primary" %>
        <%= link_to 'Delete', flat_path(flat),
              data: {:confirm => 'Are you sure?'}, :method => :delete , class: "btn btn-danger"%>
        <br>
      <% end %>

<h3><%= link_to 'add a new flat', new_flat_path %></h3>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<h1>Flats#new</h1>
<p>Find me in app/views/flats/new.html.erb</p>

app/views/flats/show.html.erb
<h1>Flats#show</h1>
<p>Find me in app/views/flats/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>